In [1]:
import pandas as pd
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv')
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv')
import tensorflow as tf
# y_train = dftrain.pop('survived')
# y_eval = dfeval.pop('survived')
dftrain.head()

,survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,0,male,22.0,1,0,7.2500,Third,unknown,Southampton,n
1,1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
2,1,female,26.0,0,0,7.9250,Third,unknown,Southampton,y
3,1,female,35.0,1,0,53.1000,First,C,Southampton,n
4,0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y

In [8]:
y_train = dftrain.pop('survived')
y_eval = dfeval.pop('survived')
dftrain.head()

,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,male,22.0,1,0,7.2500,Third,unknown,Southampton,n
1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
2,female,26.0,0,0,7.9250,Third,unknown,Southampton,y
3,female,35.0,1,0,53.1000,First,C,Southampton,n
4,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y

In [9]:
CATEGORICAL_COLUMNS = ['sex', 'n_siblings_spouses', 'parch', 'class', 'deck', 'embark_town', 'alone']
NUMERIC_COLUMNS = ['age', 'fare']
feature_columns = []

# Categorical columns
for feature_name in CATEGORICAL_COLUMNS:
    vocabulary = dftrain[feature_name].unique()
    feature_columns.append(
        tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary)
    )

# Numeric columns
for feature_name in NUMERIC_COLUMNS:
    feature_columns.append(
    tf.feature_column.numeric_column(feature_name, dtype=tf.float32)
    )

print(feature_columns)

[VocabularyListCategoricalColumn(key='sex', vocabulary_list=('male', 'female'), dtype=tf.string, default_value=-1, num_oov_buckets=0), VocabularyListCategoricalColumn(key='n_siblings_spouses', vocabulary_list=(1, 0, 3, 4, 2, 5, 8), dtype=tf.int64, default_value=-1, num_oov_buckets=0), VocabularyListCategoricalColumn(key='parch', vocabulary_list=(0, 1, 2, 5, 3, 4), dtype=tf.int64, default_value=-1, num_oov_buckets=0), VocabularyListCategoricalColumn(key='class', vocabulary_list=('Third', 'First', 'Second'), dtype=tf.string, default_value=-1, num_oov_buckets=0), VocabularyListCategoricalColumn(key='deck', vocabulary_list=('unknown', 'C', 'G', 'A', 'B', 'D', 'F', 'E'), dtype=tf.string, default_value=-1, num_oov_buckets=0), VocabularyListCategoricalColumn(key='embark_town', vocabulary_list=('Southampton', 'Cherbourg', 'Queenstown', 'unknown'), dtype=tf.string, default_value=-1, num_oov_buckets=0), VocabularyListCategoricalColumn(key='alone', vocabulary_list=('n', 'y'), dtype=tf.string, default_value=-1, num_oov_buckets=0), NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), NumericColumn(key='fare', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [ ]:
dftrain[feature_name].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.4583,  21.075 ,
        11.1333,  30.0708,  16.7   ,   8.05  ,  31.275 ,   7.8542,
        29.125 ,  13.    ,  18.    ,   7.225 ,  26.    ,  35.5   ,
        31.3875, 263.    ,   7.8792,   7.8958,  27.7208, 146.5208,
         7.75  ,  10.5   ,  82.1708,  52.    ,   7.2292,  11.2417,
         9.475 ,  21.    ,  41.5792,  15.5   ,  21.6792,  17.8   ,
        39.6875,  76.7292,  61.9792,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  56.4958,
         7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,
        47.1   ,  34.375 ,  61.175 ,  34.6542,  63.3583,  23.    ,
        77.2875,   8.6542,   7.775 ,  24.15  ,  14.4542,  14.4583,
       247.5208,   7.1417,   6.975 ,   7.05  ,  14.5   ,  15.0458,
        26.2833,   9.2167,  79.2   ,   6.75  ,  11.5   ,  12.525 ,
         7.3125,  61.3792,   7.7333,  69.55  ,  16.1   ,  55.    ,
        25.4667,  28.7125,   0.    ,  15.05  ,  22.025 ,  26.55  ,
         6.4958,  10.4625,  15.85  ,  18.7875,  31.    , 113.275 ,
        27.    ,   9.35  ,  13.5   ,   7.55  ,  12.275 ,   7.125 ,
        90.    ,  20.2125, 512.3292, 153.4625, 135.6333,  19.5   ,
        29.7   ,  77.9583,  20.25  ,  78.85  ,  12.875 ,  30.5   ,
        12.35  , 110.8833, 108.9   ,  24.    ,  56.9292,  83.1583,
       262.375 ,  26.25  , 164.8667, 134.5   ,   6.2375,  20.525 ,
        23.25  , 133.65  ,  66.6   ,  75.25  ,  69.3   , 211.5   ,
       227.525 ,   7.7292,  12.    , 120.    ,   7.7958,  18.75  ,
         6.8583,  32.5   ,  55.9   ,   8.1125,  19.2583,  27.75  ,
        89.1042,  51.8625,  38.5   ,   7.725 ,  13.7917,   7.0458,
        12.2875,   9.5875,  91.0792,  15.9   ,  19.9667,  49.5042,
       151.55  ,  59.4   ,   7.4958,  34.0208,  93.5   ,  57.9792,
       221.7792,  22.3583, 106.425 ,  49.5   ,  71.    ,  13.8625,
         7.8292,  39.6   ,  79.65  ,  17.4   ,  51.4792,  26.3875,
        30.    ,  40.125 ,  15.    ,  78.2667,  33.    ,  15.55  ,
        65.    ,  14.4   ,  15.7417,  32.3208,   7.0542,   8.4333,
        25.5875,  39.    ,   9.8417,   9.225 ,  10.1708, 211.3375,
        57.    ,  13.4167,  26.2875,   7.7417,   9.4833,   8.3625,
        23.45  ,  20.575 ,  30.6958,  25.9292,   8.6833,   7.8875,
        37.0042,   6.95  ,   8.3   ,   6.4375,  39.4   ,  14.1083,
        13.8583,  50.4958,  52.5542,   5.    ,   9.8458,  10.5167])

: